application: simhammer
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "5d 12h"

handlers:

- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/.*

- url: /.*
  script: server.application

libraries:
- name: webapp2
  version: "2.5.2"